export const BG_COLOR = "#E9EBF8"
export const FG_COLOR = "#3772FF"

// src/data/multilingualChatbotKeywords.ts

export const multilingualChatbotResponses = new Map<string, string>([

    // --- German (de) ---
    ['vergewaltigung', 'Das ist ein schwerwiegender Übergriff. Bitte suchen Sie umgehend professionelle Hilfe, wie z.B. bei einem Krisendienst oder der Polizei.'],
    ['erpressung', 'Erpressung ist illegal und Sie sind nicht allein. Dokumentieren Sie alles und suchen Sie rechtlichen Rat bei einer Beratungsstelle.'],
    ['gewalt', 'Gewalt ist inakzeptabel. Ihre Sicherheit ist das Wichtigste; überlegen Sie, ob Sie die Notrufnummer 110 wählen sollten.'],
    ['zwang', 'Niemand darf Sie zu etwas zwingen. Es gibt Organisationen, die Ihnen helfen können, sich aus Zwangssituationen zu befreien.'],
    ['schläge', 'Körperliche Gewalt ist ein Verbrechen. Bitte suchen Sie medizinische Hilfe und erwägen Sie eine Anzeige.'],
    ['drohungen', 'Drohungen sind ernst zu nehmen und können strafbar sein. Bewahren Sie Beweise auf und suchen Sie rechtlichen Beistand.'],
    ['sucht', 'Sucht ist eine Krankheit, die behandelt werden kann. Es gibt Suchtberatungsstellen, die Ihnen anonyme Unterstützung anbieten.'],
    ['gesundheit', 'Ihre Gesundheit ist wichtig. Denken Sie an regelmäßige Vorsorgeuntersuchungen und sicheren Geschlechtsverkehr.'],
    ['krankheit', 'Wenn Sie sich krank fühlen, suchen Sie bitte einen Arzt auf. Es gibt spezielle Angebote für Sexarbeiter*innen.'],
    ['sti', 'Der Schutz vor STIs ist essenziell. Lassen Sie sich regelmäßig testen und verwenden Sie immer Kondome.'],
    ['geschlechtskrankheit', 'Der Schutz vor Geschlechtskrankheiten ist essenziell. Lassen Sie sich regelmäßig testen und verwenden Sie immer Kondome.'],
    ['kondome', 'Kondome sind Ihr wichtigster Schutz. Bestehen Sie immer auf deren Verwendung und haben Sie eigene dabei.'],
    ['geldprobleme', 'Finanzielle Sorgen sind belastend, aber es gibt Hilfe. Kontaktieren Sie eine Schuldnerberatung oder soziale Dienste.'],
    ['wohnung', 'Ein sicherer Wohnraum ist grundlegend. Wenn Sie Schwierigkeiten haben, gibt es Hilfsangebote für Wohnungslose oder in Not geratene Menschen.'],
    ['ausstieg', 'Wenn Sie einen Ausstieg aus der Sexarbeit wünschen, gibt es spezialisierte Beratungsstellen, die Sie auf diesem Weg begleiten.'],
    ['beratung', 'Eine gute Beratung kann viel bewirken. Wir können Ihnen Adressen von spezialisierten Beratungsstellen nennen.'],
    ['rechte', 'Auch als Sexarbeiter*in haben Sie Rechte. Informieren Sie sich über das Prostituiertenschutzgesetz und Ihre rechtliche Situation.'],
    ['anmeldung', 'Die Anmeldung nach dem Prostituiertenschutzgesetz kann Ihnen bestimmte Rechte und Absicherungen geben. Lassen Sie sich dazu beraten.'],
    ['polizei', 'In Notfällen oder bei Straftaten zögern Sie nicht, die Polizei unter 110 zu rufen.'],
    ['vertrag', 'Formelle Verträge sind in der Sexarbeit selten, aber Absprachen sollten klar sein. Bei Unklarheiten suchen Sie rechtlichen Rat.'],
    ['diskriminierung', 'Diskriminierung ist inakzeptabel. Wenn Sie sich diskriminiert fühlen, können Sie sich an Antidiskriminierungsstellen wenden.'],
    ['hilfe', 'Wir sind hier, um Ihnen zu helfen. Beschreiben Sie Ihr Anliegen genauer, damit ich die passende Unterstützung finden kann.'],
    ['notfall', 'Im akuten Notfall wählen Sie bitte sofort die 110 (Polizei) oder 112 (Rettungsdienst).'],
    ['isolation', 'Gefühle der Isolation sind schwer. Suchen Sie den Kontakt zu anderen Sexarbeiter*innen oder zu Support-Gruppen.'],
    ['online-sicherheit', 'Ihre Sicherheit im Internet ist wichtig. Teilen Sie keine unnötigen persönlichen Daten und nutzen Sie sichere Passwörter.'],
    ['selbstfürsorge', 'Ihre mentale und physische Gesundheit ist entscheidend. Nehmen Sie sich Zeit für sich und suchen Sie bei Bedarf psychologische Hilfe.'],
  
    // --- English (en) ---
    ['rape', 'This is a serious assault. Please seek professional help immediately, such as a crisis service or the police.'],
    ['blackmail', 'Blackmail is illegal, and you are not alone. Document everything and seek legal advice from a counseling center.'],
    ['violence', 'Violence is unacceptable. Your safety is paramount; consider whether you should call the emergency number 110.'],
    ['coercion', 'No one can force you to do anything. There are organizations that can help you break free from coercive situations.'],
    ['beating', 'Physical violence is a crime. Please seek medical help and consider filing a report.'],
    ['threats', 'Threats should be taken seriously and can be punishable. Preserve evidence and seek legal assistance.'],
    ['addiction', 'Addiction is a disease that can be treated. There are addiction counseling centers that offer anonymous support.'],
    ['health', 'Your health is important. Remember to get regular check-ups and practice safe sex.'],
    ['illness', 'If you feel ill, please see a doctor. There are special services for sex workers.'],
    ['sti', 'Protection against STIs is essential. Get tested regularly and always use condoms.'],
    ['sexual disease', 'Protection against sexually transmitted diseases is essential. Get tested regularly and always use condoms.'],
    ['condoms', 'Condoms are your most important protection. Always insist on their use and carry your own.'],
    ['money problems', 'Financial worries are stressful, but help is available. Contact a debt counseling service or social services.'],
    ['housing', 'Safe housing is fundamental. If you are struggling, there are assistance programs for homeless people or those in need.'],
    ['exit', 'If you wish to exit sex work, there are specialized counseling centers that can accompany you on this path.'],
    ['counseling', 'Good counseling can make a big difference. We can provide you with addresses of specialized counseling centers.'],
    ['rights', 'Even as a sex worker, you have rights. Inform yourself about the Prostitute Protection Act and your legal situation.'],
    ['registration', 'Registration under the Prostitute Protection Act can provide you with certain rights and safeguards. Seek advice on this.'],
    ['police', 'In emergencies or in the case of crimes, do not hesitate to call the police at 110 (or 999 in the UK, 911 in the US).'],
    ['contract', 'Formal contracts are rare in sex work, but agreements should be clear. If in doubt, seek legal advice.'],
    ['discrimination', 'Discrimination is unacceptable. If you feel discriminated against, you can contact anti-discrimination agencies.'],
    ['help', 'We are here to help you. Please describe your concern in more detail so I can find the right support.'],
    ['emergency', 'In an acute emergency, please call 110 (police) or 112 (emergency services) immediately.'],
    ['isolation', 'Feelings of isolation are difficult. Seek contact with other sex workers or support groups.'],
    ['online safety', 'Your online safety is important. Do not share unnecessary personal data and use strong passwords.'],
    ['self-care', 'Your mental and physical health is crucial. Take time for yourself and seek psychological help if needed.'],
  
    // --- French (fr) ---
    ['viol', 'Ceci est une agression grave. Veuillez demander de l\'aide professionnelle immédiatement, par exemple auprès d\'un service de crise ou de la police.'],
    ['chantage', 'Le chantage est illégal et vous n\'êtes pas seule. Documentez tout et demandez des conseils juridiques à un centre de consultation.'],
    ['violence', 'La violence est inacceptable. Votre sécurité est primordiale ; déterminez si vous devez appeler le numéro d\'urgence 110.'],
    ['contrainte', 'Personne ne peut vous forcer à faire quoi que ce soit. Il existe des organisations qui peuvent vous aider à vous libérer des situations de contrainte.'],
    ['coups', 'La violence physique est un crime. Veuillez demander de l\'aide médicale et envisager de porter plainte.'],
    ['menaces', 'Les menaces doivent être prises au sérieux et peuvent être passibles de poursuites. Conservez les preuves et demandez une assistance juridique.'],
    ['dépendance', 'La dépendance est une maladie qui peut être traitée. Il existe des centres de consultation en toxicomanie qui offrent un soutien anonyme.'],
    ['santé', 'Votre santé est importante. Pensez à des examens de contrôle réguliers et à des rapports sexuels protégés.'],
    ['maladie', 'Si vous vous sentez malade, veuillez consulter un médecin. Il existe des services spéciaux pour les travailleuses du sexe.'],
    ['ist', 'La protection contre les IST est essentielle. Faites-vous tester régulièrement et utilisez toujours des préservatifs.'],
    ['maladie sexuellement transmissible', 'La protection contre les maladies sexuellement transmissibles est essentielle. Faites-vous tester régulièrement et utilisez toujours des préservatifs.'],
    ['préservatifs', 'Les préservatifs sont votre protection la plus importante. Insistez toujours sur leur utilisation et ayez les vôtres sur vous.'],
    ['problèmes d\'argent', 'Les soucis financiers sont stressants, mais de l\'aide est disponible. Contactez un service de conseil en endettement ou les services sociaux.'],
    ['logement', 'Un logement sûr est fondamental. Si vous rencontrez des difficultés, il existe des programmes d\'aide pour les personnes sans abri ou en détresse.'],
    ['sortie', 'Si vous souhaitez sortir du travail du sexe, il existe des centres de consultation spécialisés qui peuvent vous accompagner sur cette voie.'],
    ['conseil', 'Un bon conseil peut faire une grande différence. Nous pouvons vous fournir les adresses de centres de consultation spécialisés.'],
    ['droits', 'Même en tant que travailleuse du sexe, vous avez des droits. Informez-vous sur la loi sur la protection de la prostitution et votre situation juridique.'],
    ['enregistrement', 'L\'enregistrement en vertu de la loi sur la protection de la prostitution peut vous conférer certains droits et garanties. Demandez conseil à ce sujet.'],
    ['police', 'En cas d\'urgence ou de crimes, n\'hésitez pas à appeler la police au 17 (ou 112).'],
    ['contrat', 'Les contrats formels sont rares dans le travail du sexe, mais les accords doivent être clairs. En cas de doute, demandez des conseils juridiques.'],
    ['discrimination', 'La discrimination est inacceptable. Si vous vous sentez discriminée, vous pouvez contacter les organismes de lutte contre la discrimination.'],
    ['aide', 'Nous sommes là pour vous aider. Veuillez décrire votre préoccupation plus en détail afin que je puisse trouver le soutien approprié.'],
    ['urgence', 'En cas d\'urgence aiguë, veuillez appeler immédiatement le 110 (police) ou le 112 (services d\'urgence).'],
    ['isolement', 'Les sentiments d\'isolement sont difficiles. Cherchez à contacter d\'autres travailleuses du sexe ou des groupes de soutien.'],
    ['sécurité en ligne', 'Votre sécurité en ligne est importante. Ne partagez pas de données personnelles inutiles et utilisez des mots de passe forts.'],
    ['autosoins', 'Votre santé mentale et physique est cruciale. Prenez du temps pour vous et demandez de l\'aide psychologique si nécessaire.'],
  
    // --- Portuguese (pt) ---
    ['violação', 'Isto é um ataque grave. Por favor, procure ajuda profissional imediatamente, como um serviço de crise ou a polícia.'],
    ['chantagem', 'A chantagem é ilegal e você não está sozinha. Documente tudo e procure aconselhamento jurídico num centro de aconselhamento.'],
    ['violência', 'A violência é inaceitável. A sua segurança é primordial; considere se deve ligar para o número de emergência 110.'],
    ['coerção', 'Ninguém pode forçá-la a fazer nada. Existem organizações que podem ajudá-la a libertar-se de situações de coerção.'],
    ['espancamento', 'A violência física é um crime. Por favor, procure ajuda médica e considere apresentar uma queixa.'],
    ['ameaças', 'As ameaças devem ser levadas a sério e podem ser puníveis. Preserve as provas e procure assistência jurídica.'],
    ['vício', 'O vício é uma doença que pode ser tratada. Existem centros de aconselhamento sobre dependência que oferecem apoio anónimo.'],
    ['saúde', 'A sua saúde é importante. Lembre-se de fazer exames regulares e praticar sexo seguro.'],
    ['doença', 'Se se sentir doente, por favor, consulte um médico. Existem serviços especiais para trabalhadores do sexo.'],
    ['ist', 'A proteção contra ISTs é essencial. Faça testes regularmente e use sempre preservativos.'],
    ['doença sexualmente transmissível', 'A proteção contra doenças sexualmente transmissíveis é essencial. Faça testes regularmente e use sempre preservativos.'],
    ['preservativos', 'Os preservativos são a sua proteção mais importante. Insista sempre na sua utilização e tenha os seus próprios.'],
    ['problemas financeiros', 'As preocupações financeiras são stressantes, mas há ajuda disponível. Contacte um serviço de aconselhamento de dívidas ou serviços sociais.'],
    ['habitação', 'Uma habitação segura é fundamental. Se estiver com dificuldades, existem programas de assistência para pessoas sem-abrigo ou em necessidade.'],
    ['saída', 'Se deseja sair do trabalho sexual, existem centros de aconselhamento especializados que podem acompanhá-la neste caminho.'],
    ['aconselhamento', 'Um bom aconselhamento pode fazer uma grande diferença. Podemos fornecer-lhe endereços de centros de aconselhamento especializados.'],
    ['direitos', 'Mesmo como trabalhadora do sexo, você tem direitos. Informe-se sobre a Lei de Proteção da Prostituição e a sua situação legal.'],
    ['registo', 'O registo ao abrigo da Lei de Proteção da Prostituição pode proporcionar-lhe certos direitos e salvaguardas. Procure aconselhamento sobre isso.'],
    ['polícia', 'Em emergências ou em caso de crimes, não hesite em ligar para a polícia no número 110 (ou 112 em Portugal, 190 no Brasil).'],
    ['contrato', 'Contratos formais são raros no trabalho sexual, mas os acordos devem ser claros. Em caso de dúvida, procure aconselhamento jurídico.'],
    ['discriminação', 'A discriminação é inaceitável. Se se sentir discriminada, pode contactar as agências de anti-discriminação.'],
    ['ajuda', 'Estamos aqui para a ajudar. Por favor, descreva a sua preocupação mais detalhadamente para que eu possa encontrar o apoio adequado.'],
    ['emergência', 'Numa emergência aguda, por favor, ligue imediatamente para o 110 (polícia) ou 112 (serviços de emergência).'],
    ['isolamento', 'Os sentimentos de isolamento são difíceis. Procure contacto com outros trabalhadores do sexo ou grupos de apoio.'],
    ['segurança online', 'A sua segurança online é importante. Não partilhe dados pessoais desnecessários e use senhas fortes.'],
    ['autocuidado', 'A sua saúde mental e física é crucial. Reserve um tempo para si e procure ajuda psicológica se necessário.'],
  
    // --- Spanish (es) ---
    ['violación', 'Esto es una agresión grave. Por favor, busque ayuda profesional de inmediato, como un servicio de crisis o la policía.'],
    ['chantaje', 'El chantaje es ilegal y no está sola. Documente todo y busque asesoramiento legal en un centro de consejería.'],
    ['violencia', 'La violencia es inaceptable. Su seguridad es primordial; considere si debe llamar al número de emergencia 110.'],
    ['coerción', 'Nadie puede obligarla a hacer nada. Hay organizaciones que pueden ayudarle a liberarse de situaciones de coerción.'],
    ['golpes', 'La violencia física es un delito. Por favor, busque ayuda médica y considere presentar una denuncia.'],
    ['amenazas', 'Las amenazas deben tomarse en serio y pueden ser punibles. Conserve las pruebas y busque asistencia legal.'],
    ['adicción', 'La adicción es una enfermedad que se puede tratar. Hay centros de asesoramiento sobre adicciones que ofrecen apoyo anónimo.'],
    ['salud', 'Su salud es importante. Recuerde hacerse chequeos regulares y practicar sexo seguro.'],
    ['enfermedad', 'Si se siente enferma, por favor, consulte a un médico. Hay servicios especiales para trabajadoras sexuales.'],
    ['its', 'La protección contra las ITS es esencial. Hágase pruebas regularmente y use siempre condones.'],
    ['enfermedad de transmisión sexual', 'La protección contra las enfermedades de transmisión sexual es esencial. Hágase pruebas regularmente y use siempre condones.'],
    ['condones', 'Los condones son su protección más importante. Insista siempre en su uso y lleve los suyos propios.'],
    ['problemas de dinero', 'Las preocupaciones financieras son estresantes, pero hay ayuda disponible. Contacte con un servicio de asesoramiento de deudas o servicios sociales.'],
    ['vivienda', 'Una vivienda segura es fundamental. Si tiene dificultades, hay programas de asistencia para personas sin hogar o en necesidad.'],
    ['salida', 'Si desea salir del trabajo sexual, hay centros de asesoramiento especializados que pueden acompañarla en este camino.'],
    ['asesoramiento', 'Un buen asesoramiento puede marcar una gran diferencia. Podemos proporcionarle direcciones de centros de asesoramiento especializados.'],
    ['derechos', 'Incluso como trabajadora sexual, usted tiene derechos. Infórmese sobre la Ley de Protección de la Prostitución y su situación legal.'],
    ['registro', 'El registro bajo la Ley de Protección de la Prostitución puede proporcionarle ciertos derechos y salvaguardias. Busque asesoramiento al respecto.'],
    ['policía', 'En emergencias o en caso de delitos, no dude en llamar a la policía al 112 (o 091 en España, 911 en América).'],
    ['contrato', 'Los contratos formales son raros en el trabajo sexual, pero los acuerdos deben ser claros. En caso de duda, busque asesoramiento legal.'],
    ['discriminación', 'La discriminación es inaceptable. Si se siente discriminada, puede contactar con las agencias antidiscriminación.'],
    ['ayuda', 'Estamos aquí para ayudarle. Por favor, describa su preocupación con más detalle para que pueda encontrar el apoyo adecuado.'],
    ['emergencia', 'En una emergencia aguda, por favor, llame inmediatamente al 110 (policía) o 112 (servicios de emergencia).'],
    ['aislamiento', 'Los sentimientos de aislamiento son difíciles. Busque contacto con otras trabajadoras sexuales o grupos de apoyo.'],
    ['seguridad en línea', 'Su seguridad en línea es importante. No comparta datos personales innecesarios y use contraseñas seguras.'],
    ['autocuidado', 'Su salud mental y física es crucial. Tómese tiempo para usted y busque ayuda psicológica si es necesario.'],
  
    // --- Bulgarian (bg) ---
    ['изнасилване', 'Това е сериозно посегателство. Моля, потърсете незабавно професионална помощ, например от кризисен център или полицията.'],
    ['изнудване', 'Изнудването е незаконно и не сте сама. Документирайте всичко и потърсете правен съвет от консултативен център.'],
    ['насилие', 'Насилието е неприемливо. Вашата безопасност е от първостепенно значение; обмислете дали да не се обадите на спешен телефон 112.'],
    ['принуда', 'Никой не може да ви принуждава да правите каквото и да било. Има организации, които могат да ви помогнат да се освободите от ситуации на принуда.'],
    ['побой', 'Физическото насилие е престъпление. Моля, потърсете медицинска помощ и обмислете подаване на сигнал.'],
    ['заплахи', 'Заплахите трябва да се приемат сериозно и могат да бъдат наказуеми. Запазете доказателства и потърсете правна помощ.'],
    ['зависимост', 'Зависимостта е болест, която може да бъде лекувана. Има консултативни центрове за зависими, които предлагат анонимна подкрепа.'],
    ['здраве', 'Вашето здраве е важно. Не забравяйте да правите редовни прегледи и да практикувате безопасен секс.'],
    ['болест', 'Ако се чувствате болна, моля, посетете лекар. Има специални услуги за сексуални работници.'],
    ['ппп', 'Защитата от ППП е от съществено значение. Тествайте се редовно и винаги използвайте презервативи.'],
    ['полово предавана болест', 'Защитата от полово предавани болести е от съществено значение. Тествайте се редовно и винаги използвайте презервативи.'],
    ['презервативи', 'Презервативите са вашата най-важна защита. Винаги настоявайте за тяхното използване и носете свои собствени.'],
    ['финансови проблеми', 'Финансовите притеснения са стресиращи, но има помощ. Свържете се със служба за консултиране по дългове или социални служби.'],
    ['жилище', 'Сигурното жилище е от основно значение. Ако изпитвате затруднения, има програми за подпомагане на бездомни или нуждаещи се хора.'],
    ['напускане', 'Ако желаете да напуснете секс работата, има специализирани консултативни центрове, които могат да ви придружат по този път.'],
    ['консултация', 'Добрата консултация може да направи голяма разлика. Можем да ви предоставим адреси на специализирани консултативни центрове.'],
    ['права', 'Дори като сексуална работничка имате права. Информирайте се за Закона за защита на проституцията и вашето правно положение.'],
    ['регистрация', 'Регистрацията съгласно Закона за защита на проституцията може да ви осигури определени права и гаранции. Потърсете съвет по този въпрос.'],
    ['полиция', 'При извънредни ситуации или в случай на престъпления, не се колебайте да се обадите на полицията на 112.'],
    ['договор', 'Официалните договори са рядкост в секс работата, но споразуменията трябва да са ясни. В случай на съмнение, потърсете правен съвет.'],
    ['дискриминация', 'Дискриминацията е неприемлива. Ако се чувствате дискриминирани, можете да се свържете с агенции за борба с дискриминацията.'],
    ['помощ', 'Ние сме тук, за да ви помогнем. Моля, опишете по-подробно проблема си, за да мога да намеря подходящата подкрепа.'],
    ['спешен случай', 'При остър спешен случай, моля, незабавно се обадете на 112 (полиция/бърза помощ).'],
    ['изолация', 'Чувството за изолация е трудно. Потърсете контакт с други сексуални работници или групи за подкрепа.'],
    ['онлайн безопасност', 'Вашата онлайн безопасност е важна. Не споделяйте ненужни лични данни и използвайте силни пароли.'],
    ['самообслужване', 'Вашето психическо и физическо здраве е от решаващо значение. Отделете време за себе си и потърсете психологическа помощ, ако е необходимо.'],
  
    // --- Romanian (ro) ---
    ['viol', 'Acesta este un atac grav. Vă rugăm să căutați ajutor profesional imediat, cum ar fi un serviciu de criză sau poliția.'],
    ['șantaj', 'Șantajul este ilegal și nu sunteți singură. Documentați totul și căutați sfaturi juridice de la un centru de consiliere.'],
    ['violență', 'Violența este inacceptabilă. Siguranța dumneavoastră este primordială; luați în considerare dacă ar trebui să apelați numărul de urgență 112.'],
    ['constrângere', 'Nimeni nu vă poate forța să faceți nimic. Există organizații care vă pot ajuta să vă eliberați din situații de constrângere.'],
    ['lovituri', 'Violența fizică este o crimă. Vă rugăm să căutați ajutor medical și să luați în considerare depunerea unei plângeri.'],
    ['amenințări', 'Amenințările trebuie luate în serios și pot fi pedepsibile. Păstrați dovezi și căutați asistență juridică.'],
    ['dependență', 'Dependența este o boală care poate fi tratată. Există centre de consiliere pentru dependență care oferă sprijin anonim.'],
    ['sănătate', 'Sănătatea dumneavoastră este importantă. Nu uitați să faceți controale regulate și să practicați sexul sigur.'],
    ['boală', 'Dacă vă simțiți rău, vă rugăm să consultați un medic. Există servicii speciale pentru lucrătorii sexuali.'],
    ['bts', 'Protecția împotriva BTS-urilor este esențială. Faceți-vă teste regulate și folosiți întotdeauna prezervative.'],
    ['boală cu transmitere sexuală', 'Protecția împotriva bolilor cu transmitere sexuală este esențială. Faceți-vă teste regulate și folosiți întotdeauna prezervative.'],
    ['prezervative', 'Prezervativele sunt cea mai importantă protecție a dumneavoastră. Insistați întotdeauna asupra utilizării lor și purtați-le pe ale dumneavoastră.'],
    ['probleme financiare', 'Îngrijorările financiare sunt stresante, dar există ajutor. Contactați un serviciu de consiliere pentru datorii sau serviciile sociale.'],
    ['locuință', 'O locuință sigură este fundamentală. Dacă întâmpinați dificultăți, există programe de asistență pentru persoanele fără adăpost sau aflate în nevoie.'],
    ['ieșire', 'Dacă doriți să ieșiți din munca sexuală, există centre de consiliere specializate care vă pot însoți pe această cale.'],
    ['consiliere', 'O bună consiliere poate face o mare diferență. Vă putem oferi adresele centrelor de consiliere specializate.'],
    ['drepturi', 'Chiar și ca lucrătoare sexuală, aveți drepturi. Informați-vă despre Legea privind protecția prostituției și situația dumneavoastră legală.'],
    ['înregistrare', 'Înregistrarea conform Legii privind protecția prostituției vă poate oferi anumite drepturi și garanții. Solicitați sfaturi în acest sens.'],
    ['poliție', 'În caz de urgențe sau infracțiuni, nu ezitați să apelați poliția la 112.'],
    ['contract', 'Contractele formale sunt rare în munca sexuală, dar acordurile ar trebui să fie clare. În caz de îndoială, căutați sfaturi juridice.'],
    ['discriminare', 'Discriminarea este inacceptabilă. Dacă vă simțiți discriminată, puteți contacta agențiile antidiscriminare.'],
    ['ajutor', 'Suntem aici pentru a vă ajuta. Vă rugăm să descrieți mai detaliat preocuparea dumneavoastră pentru a putea găsi sprijinul potrivit.'],
    ['urgență', 'Într-o urgență acută, vă rugăm să apelați imediat la 112 (poliție/servicii de urgență).'],
    ['izolare', 'Sentimentele de izolare sunt dificile. Căutați contactul cu alți lucrători sexuali sau grupuri de sprijin.'],
    ['siguranță online', 'Siguranța dumneavoastră online este importantă. Nu partajați date personale inutile și utilizați parole puternice.'],
    ['auto-îngrijire', 'Sănătatea dumneavoastră mentală și fizică este crucială. Acordați-vă timp și căutați ajutor psihologic dacă este necesar.'],
  
    // --- Hungarian (hu) ---
    ['nemierőszak', 'Ez súlyos támadás. Kérjük, azonnal kérjen szakmai segítséget, például egy krízisszolgálattól vagy a rendőrségtől.'],
    ['zsarolás', 'A zsarolás illegális, és nem vagy egyedül. Dokumentáljon mindent, és kérjen jogi tanácsot egy tanácsadó központtól.'],
    ['erőszak', 'Az erőszak elfogadhatatlan. Az Ön biztonsága a legfontosabb; fontolja meg, hogy hívja-e a 112-es segélyhívó számot.'],
    ['kényszer', 'Senki sem kényszerítheti semmire. Vannak szervezetek, amelyek segíthetnek megszabadulni a kényszerhelyzetektől.'],
    ['verés', 'A fizikai erőszak bűncselekmény. Kérjük, keressen orvosi segítséget és fontolja meg feljelentést.'],
    ['fenyegetések', 'A fenyegetéseket komolyan kell venni, és büntethetőek. Őrizze meg a bizonyítékokat, és kérjen jogi segítséget.'],
    ['függőség', 'A függőség betegség, ami kezelhető. Vannak addiktológiai tanácsadó központok, amelyek névtelen támogatást nyújtanak.'],
    ['egészség', 'Az Ön egészsége fontos. Gondoljon a rendszeres szűrővizsgálatokra és a biztonságos szexre.'],
    ['betegség', 'Ha betegnek érzi magát, kérjük, forduljon orvoshoz. Vannak speciális szolgáltatások a szexuális dolgozók számára.'],
    ['nemibetegség', 'A nemi betegségek elleni védelem alapvető. Rendszeresen teszteltesse magát, és mindig használjon óvszert.'],
    ['szexuális úton terjedő betegség', 'A szexuális úton terjedő betegségek elleni védelem alapvető. Rendszeresen teszteltesse magát, és mindig használjon óvszert.'],
    ['óvszer', 'Az óvszer a legfontosabb védelme. Mindig ragaszkodjon a használatához, és legyen Önnél saját.'],
    ['pénzügyi problémák', 'A pénzügyi gondok stresszesek, de van segítség. Lépjen kapcsolatba egy adósság-tanácsadó szolgálattal vagy szociális szolgáltatásokkal.'],
    ['lakás', 'A biztonságos lakhatás alapvető. Ha nehézségei vannak, vannak segélyprogramok hajléktalanok vagy rászorulók számára.'],
    ['kilépés', 'Ha szeretne kilépni a szexmunkából, vannak szakosodott tanácsadó központok, amelyek elkísérik ezen az úton.'],
    ['tanácsadás', 'Egy jó tanácsadás sokat segíthet. Tudunk Önnek szakosodott tanácsadó központok címeit megadni.'],
    ['jogok', 'Szexmunkásként is vannak jogai. Tájékozódjon a Prostitúciós Védelmi Törvényről és jogi helyzetéről.'],
    ['regisztráció', 'A prostitúció védelmi törvény szerinti regisztráció bizonyos jogokat és garanciákat biztosíthat Önnek. Kérjen tanácsot ezzel kapcsolatban.'],
    ['rendőrség', 'Vészhelyzet esetén vagy bűncselekmény esetén ne habozzon hívni a rendőrséget a 112-es számon.'],
    ['szerződés', 'A hivatalos szerződések ritkák a szexmunkában, de a megállapodásoknak egyértelműnek kell lenniük. Kétség esetén kérjen jogi tanácsot.'],
    ['diszkrimináció', 'A diszkrimináció elfogadhatatlan. Ha diszkriminációt tapasztal, forduljon diszkriminációellenes ügynökségekhez.'],
    ['segítség', 'Azért vagyunk itt, hogy segítsünk Önnek. Kérjük, írja le részletesebben a problémáját, hogy megtaláljam a megfelelő támogatást.'],
    ['vészhelyzet', 'Akut vészhelyzet esetén kérjük, azonnal hívja a 112-es (rendőrség/mentőszolgálat) számot.'],
    ['elszigeteltség', 'Az elszigeteltség érzése nehéz. Keressen kapcsolatot más szexmunkásokkal vagy támogató csoportokkal.'],
    ['online biztonság', 'Az Ön online biztonsága fontos. Ne osszon meg felesleges személyes adatokat, és használjon erős jelszavakat.'],
    ['öngondoskodás', 'Mentális és fizikai egészsége létfontosságú. Szánjon időt magára, és szükség esetén kérjen pszichológiai segítséget.'],
  
    // --- Russian (ru) ---
    ['изнасилование', 'Это серьезное нападение. Пожалуйста, немедленно обратитесь за профессиональной помощью, например, в кризисную службу или полицию.'],
    ['шантаж', 'Шантаж незаконен, и вы не одиноки. Документируйте все и обратитесь за юридической консультацией в центр.'],
    ['насилие', 'Насилие неприемлемо. Ваша безопасность превыше всего; подумайте, стоит ли звонить по номеру экстренной помощи 112.'],
    ['принуждение', 'Никто не может вас ни к чему принуждать. Существуют организации, которые могут помочь вам освободиться от принудительных ситуаций.'],
    ['побои', 'Физическое насилие - это преступление. Пожалуйста, обратитесь за медицинской помощью и рассмотрите возможность подачи заявления.'],
    ['угрозы', 'Угрозы следует воспринимать всерьез и они могут быть наказуемы. Сохраняйте доказательства и обращайтесь за юридической помощью.'],
    ['зависимость', 'Зависимость - это болезнь, которую можно лечить. Существуют консультационные центры по зависимостям, которые предлагают анонимную поддержку.'],
    ['здоровье', 'Ваше здоровье важно. Не забывайте о регулярных обследованиях и безопасном сексе.'],
    ['болезнь', 'Если вы чувствуете себя больной, пожалуйста, обратитесь к врачу. Существуют специальные услуги для секс-работников.'],
    ['иппп', 'Защита от ИППП необходима. Регулярно проходите обследования и всегда используйте презервативы.'],
    ['половая болезнь', 'Защита от половых болезней необходима. Регулярно проходите обследования и всегда используйте презервативы.'],
    ['презервативы', 'Презервативы - ваша самая важная защита. Всегда настаивайте на их использовании и имейте свои.'],
    ['проблемы с деньгами', 'Финансовые заботы вызывают стресс, но помощь доступна. Обратитесь в службу консультирования по долгам или в социальные службы.'],
    ['жилье', 'Безопасное жилье является основополагающим. Если у вас возникли трудности, существуют программы помощи для бездомных или нуждающихся.'],
    ['выход', 'Если вы хотите выйти из секс-работы, есть специализированные консультационные центры, которые могут сопровождать вас на этом пути.'],
    ['консультация', 'Хорошая консультация может иметь большое значение. Мы можем предоставить вам адреса специализированных консультационных центров.'],
    ['права', 'Даже будучи секс-работником, у вас есть права. Информируйте себя о Законе о защите проституции и вашей правовой ситуации.'],
    ['регистрация', 'Регистрация в соответствии с Законом о защите проституции может предоставить вам определенные права и гарантии. Обратитесь за советом по этому вопросу.'],
    ['полиция', 'В чрезвычайных ситуациях или в случае преступлений не стесняйтесь звонить в полицию по номеру 112 (или 102).'],
    ['договор', 'Формальные договоры редки в секс-работе, но соглашения должны быть четкими. В случае сомнений, обратитесь за юридической консультацией.'],
    ['дискриминация', 'Дискриминация неприемлема. Если вы чувствуете дискриминацию, вы можете обратиться в антидискриминационные агентства.'],
    ['помощь', 'Мы здесь, чтобы помочь вам. Пожалуйста, опишите свою проблему подробнее, чтобы я мог найти подходящую поддержку.'],
    ['чрезвычайная ситуация', 'В острой чрезвычайной ситуации, пожалуйста, немедленно звоните по номеру 112 (полиция/скорая помощь).'],
    ['изоляция', 'Чувство изоляции тяжело. Ищите контакты с другими секс-работниками или группами поддержки.'],
    ['онлайн-безопасность', 'Ваша онлайн-безопасность важна. Не делитесь ненужными личными данными и используйте надежные пароли.'],
    ['самопомощь', 'Ваше психическое и физическое здоровье имеет решающее значение. Выделите время для себя и при необходимости обратитесь за психологической помощью.'],
  
    // --- Polish (pl) ---
    ['gwałt', 'To jest poważne napaść. Proszę natychmiast szukać profesjonalnej pomocy, na przykład w służbie kryzysowej lub na policji.'],
    ['szantaż', 'Szantaż jest nielegalny i nie jesteś sama. Dokumentuj wszystko i szukaj porady prawnej w centrum doradczym.'],
    ['przemoc', 'Przemoc jest niedopuszczalna. Twoje bezpieczeństwo jest najważniejsze; rozważ, czy powinieneś zadzwonić pod numer alarmowy 112.'],
    ['przymus', 'Nikt nie może cię do niczego zmuszać. Istnieją organizacje, które mogą pomóc ci uwolnić się od sytuacji przymusu.'],
    ['bicie', 'Przemoc fizyczna jest przestępstwem. Proszę szukać pomocy medycznej i rozważyć złożenie doniesienia.'],
    ['groźby', 'Groźby należy traktować poważnie i mogą być karalne. Zachowaj dowody i szukaj pomocy prawnej.'],
    ['uzależnienie', 'Uzależnienie to choroba, którą można leczyć. Istnieją ośrodki doradztwa w zakresie uzależnień, które oferują anonimowe wsparcie.'],
    ['zdrowie', 'Twoje zdrowie jest ważne. Pamiętaj o regularnych badaniach kontrolnych i bezpiecznym seksie.'],
    ['choroba', 'Jeśli czujesz się chora, proszę skonsultuj się z lekarzem. Istnieją specjalne usługi dla osób pracujących w seksie.'],
    ['choroby weneryczne', 'Ochrona przed chorobami wenerycznymi jest kluczowa. Regularnie się badaj i zawsze używaj prezerwatyw.'],
    ['choroba przenoszona drogą płciową', 'Ochrona przed chorobami przenoszonymi drogą płciową jest kluczowa. Regularnie się badaj i zawsze używaj prezerwatyw.'],
    ['prezerwatywy', 'Prezerwatywy są twoją najważniejszą ochroną. Zawsze nalegaj na ich użycie i miej swoje.'],
    ['problemy z pieniędzmi', 'Kłopoty finansowe są stresujące, ale pomoc jest dostępna. Skontaktuj się z biurem doradztwa zadłużeniowego lub służbami społecznymi.'],
    ['mieszkanie', 'Bezpieczne mieszkanie jest podstawą. Jeśli masz trudności, istnieją programy pomocy dla osób bezdomnych lub potrzebujących.'],
    ['wyjście', 'Jeśli chcesz odejść od pracy w seksie, istnieją wyspecjalizowane centra doradztwa, które mogą ci towarzyszyć na tej drodze.'],
    ['doradztwo', 'Dobre doradztwo może wiele zmienić. Możemy podać ci adresy wyspecjalizowanych ośrodków doradczych.'],
    ['prawa', 'Nawet jako osoba pracująca w seksie, masz prawa. Poinformuj się o Ustawie o ochronie prostytucji i swojej sytuacji prawnej.'],
    ['rejestracja', 'Rejestracja zgodnie z Ustawą o ochronie prostytucji może zapewnić ci pewne prawa i zabezpieczenia. Zasięgnij porady w tej sprawie.'],
    ['policja', 'W nagłych wypadkach lub w przypadku przestępstw nie wahaj się dzwonić na policję pod numer 112 (lub 997).'],
    ['umowa', 'Formalne umowy są rzadkością w pracy w seksie, ale uzgodnienia powinny być jasne. W razie wątpliwości zasięgnij porady prawnej.'],
    ['dyskryminacja', 'Dyskryminacja jest niedopuszczalna. Jeśli czujesz się dyskryminowana, możesz skontaktować się z agencjami antydyskryminacyjnymi.'],
    ['pomoc', 'Jesteśmy tutaj, aby ci pomóc. Opisz swoje zmartwienie bardziej szczegółowo, abym mógł znaleźć odpowiednie wsparcie.'],
    ['nagły wypadek', 'W nagłym wypadku proszę natychmiast zadzwonić pod numer 112 (policja/pogotowie).'],
    ['izolacja', 'Uczucia izolacji są trudne. Szukaj kontaktu z innymi osobami pracującymi w seksie lub grupami wsparcia.'],
    ['bezpieczeństwo online', 'Twoje bezpieczeństwo w Internecie jest ważne. Nie udostępniaj niepotrzebnych danych osobowych i używaj silnych haseł.'],
    ['troska o siebie', 'Twoje zdrowie psychiczne i fizyczne jest kluczowe. Poświęć czas dla siebie i w razie potrzeby poszukaj pomocy psychologicznej.'],
  
    // --- Bosnian (bs) ---
    ['silovanje', 'Ovo je ozbiljan napad. Molimo vas da odmah potražite stručnu pomoć, npr. krizne službe ili policije.'],
    ['ucjena', 'Ucjena je ilegalna i niste sami. Dokumentujte sve i potražite pravni savjet u savjetovalištu.'],
    ['nasilje', 'Nasilje je neprihvatljivo. Vaša sigurnost je najvažnija; razmislite trebate li pozvati hitni broj 112.'],
    ['prisila', 'Nitko vas ne može prisiljavati na bilo što. Postoje organizacije koje vam mogu pomoći da se oslobodite prisilnih situacija.'],
    ['batine', 'Fizičko nasilje je zločin. Molimo vas da potražite medicinsku pomoć i razmotrite podnošenje prijave.'],
    ['prijetnje', 'Prijetnje treba shvatiti ozbiljno i mogu biti kažnjive. Sačuvajte dokaze i potražite pravnu pomoć.'],
    ['ovisnost', 'Ovisnost je bolest koja se može liječiti. Postoje savjetovališta za ovisnike koja nude anonimnu podršku.'],
    ['zdravlje', 'Vaše zdravlje je važno. Redovito se pregledajte i prakticirajte siguran seks.'],
    ['bolest', 'Ako se osjećate bolesno, molimo vas da posjetite liječnika. Postoje posebne usluge za seksualne radnike.'],
    ['spolno prenosiva infekcija', 'Zaštita od SPI je ključna. Redovito se testirajte i uvijek koristite kondome.'],
    ['spolna bolest', 'Zaštita od spolnih bolesti je ključna. Redovito se testirajte i uvijek koristite kondome.'],
    ['kondomi', 'Kondomi su vaša najvažnija zaštita. Uvijek inzistirajte na njihovoj upotrebi i nosite svoje.'],
    ['novčani problemi', 'Financijske brige su stresne, ali pomoć je dostupna. Obratite se savjetovalištu za dugove ili socijalnim službama.'],
    ['stanovanje', 'Siguran smještaj je temelj. Ako imate poteškoća, postoje programi pomoći za beskućnike ili osobe u nevolji.'],
    ['izlazak', 'Ako želite napustiti seksualni rad, postoje specijalizirana savjetovališta koja vas mogu pratiti na tom putu.'],
    ['savjetovanje', 'Dobar savjet može učiniti veliku razliku. Možemo vam dati adrese specijaliziranih savjetovališta.'],
    ['prava', 'Čak i kao seksualna radnica, imate prava. Informirajte se o Zakonu o zaštiti prostitucije i svojoj pravnoj situaciji.'],
    ['registracija', 'Registracija prema Zakonu o zaštiti prostitucije može vam pružiti određena prava i zaštitu. Potražite savjet o tome.'],
    ['policija', 'U hitnim slučajevima ili u slučaju kaznenih djela, ne ustručavajte se nazvati policiju na 122 (ili 112).'],
    ['ugovor', 'Formalni ugovori su rijetkost u seksualnom radu, ali dogovori bi trebali biti jasni. U slučaju sumnje, potražite pravni savjet.'],
    ['diskriminacija', 'Diskriminacija je neprihvatljiva. Ako se osjećate diskriminirano, možete se obratiti agencijama za borbu protiv diskriminacije.'],
    ['pomoć', 'Mi smo tu da vam pomognemo. Molimo vas da detaljnije opišete svoju zabrinutost kako bih mogao pronaći odgovarajuću podršku.'],
    ['hitno', 'U akutnom hitnom slučaju, molimo vas da odmah pozovete 112 (policija/hitna pomoć).'],
    ['izolacija', 'Osjećaji izolacije su teški. Potražite kontakt s drugim seksualnim radnicima ili grupama podrške.'],
    ['online sigurnost', 'Vaša online sigurnost je važna. Nemojte dijeliti nepotrebne osobne podatke i koristite jake lozinke.'],
    ['briga o sebi', 'Vaše mentalno i fizičko zdravlje je ključno. Odvojite vrijeme za sebe i potražite psihološku pomoć ako je potrebno.'],
  
    // --- Croatian (hr) ---
    ['silovanje', 'Ovo je ozbiljan napad. Molimo vas da odmah potražite stručnu pomoć, npr. krizne službe ili policije.'],
    ['ucjena', 'Ucjena je ilegalna i niste sami. Dokumentirajte sve i potražite pravni savjet u savjetovalištu.'],
    ['nasilje', 'Nasilje je neprihvatljivo. Vaša sigurnost je najvažnija; razmislite trebate li nazvati hitni broj 112.'],
    ['prisila', 'Nitko vas ne može prisiljavati na bilo što. Postoje organizacije koje vam mogu pomoći da se oslobodite prisilnih situacija.'],
    ['udarci', 'Fizičko nasilje je zločin. Molimo vas da potražite medicinsku pomoć i razmotrite podnošenje prijave.'],
    ['prijetnje', 'Prijetnje treba shvatiti ozbiljno i mogu biti kažnjive. Sačuvajte dokaze i potražite pravnu pomoć.'],
    ['ovisnost', 'Ovisnost je bolest koja se može liječiti. Postoje savjetovališta za ovisnike koja nude anonimnu podršku.'],
    ['zdravlje', 'Vaše zdravlje je važno. Redovito se pregledajte i prakticirajte siguran seks.'],
    ['bolest', 'Ako se osjećate bolesno, molimo vas da posjetite liječnika. Postoje posebne usluge za seksualne radnike.'],
    ['spi', 'Zaštita od SPI je ključna. Redovito se testirajte i uvijek koristite kondome.'],
    ['spolna bolest', 'Zaštita od spolnih bolesti je ključna. Redovito se testirajte i uvijek koristite kondome.'],
    ['kondomi', 'Kondomi su vaša najvažnija zaštita. Uvijek inzistirajte na njihovoj upotrebi i nosite svoje.'],
    ['novčani problemi', 'Financijske brige su stresne, ali pomoć je dostupna. Obratite se savjetovalištu za dugove ili socijalnim službama.'],
    ['stanovanje', 'Siguran smještaj je temelj. Ako imate poteškoća, postoje programi pomoći za beskućnike ili osobe u nevolji.'],
    ['izlazak', 'Ako želite napustiti seksualni rad, postoje specijalizirana savjetovališta koja vas mogu pratiti na tom putu.'],
    ['savjetovanje', 'Dobar savjet može učiniti veliku razliku. Možemo vam dati adrese specijaliziranih savjetovališta.'],
    ['prava', 'Čak i kao seksualna radnica, imate prava. Informirajte se o Zakonu o zaštiti prostitucije i svojoj pravnoj situaciji.'],
    ['registracija', 'Registracija prema Zakonu o zaštiti prostitucije može vam pružiti određena prava i zaštitu. Potražite savjet o tome.'],
    ['policija', 'U hitnim slučajevima ili u slučaju kaznenih djela, ne ustručavajte se nazvati policiju na 112 (ili 192).'],
    ['ugovor', 'Formalni ugovori su rijetkost u seksualnom radu, ali dogovori bi trebali biti jasni. U slučaju sumnje, potražite pravni savjet.'],
    ['diskriminacija', 'Diskriminacija je neprihvatljiva. Ako se osjećate diskriminirano, možete se obratiti agencijama za borbu protiv diskriminacije.'],
    ['pomoć', 'Mi smo tu da vam pomognemo. Molimo vas da detaljnije opišete svoju zabrinutost kako bih mogao pronaći odgovarajuću podršku.'],
    ['hitno', 'U akutnom hitnom slučaju, molimo vas da odmah pozovete 112 (policija/hitna pomoć).'],
    ['izolacija', 'Osjećaji izolacije su teški. Potražite kontakt s drugim seksualnim radnicima ili grupama podrške.'],
    ['online sigurnost', 'Vaša online sigurnost je važna. Nemojte dijeliti nepotrebne osobne podatke i koristite jake lozinke.'],
    ['briga o sebi', 'Vaše mentalno i fizičko zdravlje je ključno. Odvojite vrijeme za sebe i potražite psihološku pomoć ako je potrebno.'],

    // --- Turkish (tr) ---
  ['tecavüz', 'Bu ciddi bir saldırıdır. Lütfen derhal profesyonel yardım alın, örneğin bir kriz servisinden veya polisten.'],
  ['şantaj', 'Şantaj yasa dışıdır ve yalnız değilsiniz. Her şeyi belgeleyin ve bir danışma merkezinden hukuki destek alın.'],
  ['şiddet', 'Şiddet kabul edilemez. Güvenliğiniz her şeyden önemlidir; 112 acil durum numarasını arayıp aramayacağınızı düşünün.'],
  ['zorlama', 'Kimse sizi hiçbir şeye zorlayamaz. Zorlama durumlarından kurtulmanız için size yardımcı olabilecek kuruluşlar var.'],
  ['dayak', 'Fiziksel şiddet bir suçtur. Lütfen tıbbi yardım alın ve şikayette bulunmayı düşünün.'],
  ['tehditler', 'Tehditler ciddiye alınmalı ve cezalandırılabilir. Kanıtları saklayın ve hukuki yardım alın.'],
  ['bağımlılık', 'Bağımlılık tedavi edilebilen bir hastalıktır. Anonim destek sunan bağımlılık danışma merkezleri bulunmaktadır.'],
  ['sağlık', 'Sağlığınız önemlidir. Düzenli kontrolleri ve güvenli cinsel ilişkiyi unutmayın.'],
  ['hastalık', 'Eğer kendinizi hasta hissediyorsanız, lütfen bir doktora görünün. Seks işçileri için özel hizmetler mevcuttur.'],
  ['cinsel yolla bulaşan enfeksiyon', 'CYBE\'lere karşı korunma çok önemlidir. Düzenli olarak test yaptırın ve her zaman prezervatif kullanın.'],
  ['cinsel yolla bulaşan hastalık', 'Cinsel yolla bulaşan hastalıklara karşı korunma çok önemlidir. Düzenli olarak test yaptırın ve her zaman prezervatif kullanın.'],
  ['prezervatifler', 'Prezervatifler sizin en önemli koruyucunuzdur. Her zaman kullanımlarında ısrar edin ve yanınızda bulundurun.'],
  ['para sorunları', 'Mali sıkıntılar streslidir, ancak yardım mevcuttur. Bir borç danışmanlık hizmeti veya sosyal hizmetlerle iletişime geçin.'],
  ['barınma', 'Güvenli barınma temel bir haktır. Eğer zorluk yaşıyorsanız, evsizler veya ihtiyaç sahipleri için yardım programları bulunmaktadır.'],
  ['çıkış', 'Eğer seks işçiliğinden ayrılmak istiyorsanız, bu yolda size eşlik edebilecek uzman danışma merkezleri bulunmaktadır.'],
  ['danışmanlık', 'İyi bir danışmanlık büyük fark yaratabilir. Size uzman danışma merkezlerinin adreslerini sağlayabiliriz.'],
  ['haklar', 'Seks işçisi olarak bile haklarınız vardır. Prostitüsyonu Koruma Yasası ve hukuki durumunuz hakkında bilgi edinin.'],
  ['kayıt', 'Prostitüsyonu Koruma Yasası kapsamındaki kayıt, size belirli haklar ve güvenceler sağlayabilir. Bu konuda danışmanlık alın.'],
  ['polis', 'Acil durumlarda veya suç durumlarında, 112 (veya yerel acil durum numarası) numarasını aramaktan çekinmeyin.'],
  ['sözleşme', 'Seks işçiliğinde resmi sözleşmeler nadirdir, ancak anlaşmalar açık olmalıdır. Şüphe durumunda hukuki yardım alın.'],
  ['ayrımcılık', 'Ayrımcılık kabul edilemez. Eğer kendinizi ayrımcılığa uğramış hissediyorsanız, ayrımcılık karşıtı kuruluşlarla iletişime geçebilirsiniz.'],
  ['yardım', 'Size yardım etmek için buradayız. Lütfen endişenizi daha detaylı açıklayın, böylece uygun desteği bulabilirim.'],
  ['acil durum', 'Akut bir acil durumda, lütfen derhal 112\'yi (polis/acil servis) arayın.'],
  ['izolasyon', 'İzolasyon duyguları zordur. Diğer seks işçileriyle veya destek gruplarıyla iletişime geçin.'],
  ['çevrimiçi güvenlik', 'Çevrimiçi güvenliğiniz önemlidir. Gereksiz kişisel verileri paylaşmayın ve güçlü şifreler kullanın.'],
  ['öz bakım', 'Zihinsel ve fiziksel sağlığınız çok önemlidir. Kendinize zaman ayırın ve gerektiğinde psikolojik yardım alın.'],

  // --- Albanian (sq) ---
  ['përdhunim', 'Ky është një sulm serioz. Ju lutemi, kërkoni menjëherë ndihmë profesionale, siç është një shërbim krize ose policia.'],
  ['shantazh', 'Shantazhi është i paligjshëm dhe nuk jeni vetëm. Dokumentoni gjithçka dhe kërkoni këshilla ligjore nga një qendër këshillimi.'],
  ['dhunë', 'Dhuna është e papranueshme. Siguria juaj është parësore; merrni parasysh nëse duhet të thërrisni numrin e urgjencës 112.'],
  ['detyrim', 'Askush nuk mund t\'ju detyrojë të bëni asgjë. Ka organizata që mund t\'ju ndihmojnë të çliroheni nga situatat e detyrimit.'],
  ['rrahje', 'Dhunat fizike janë krim. Ju lutemi, kërkoni ndihmë mjekësore dhe merrni parasysh bërjen e një denoncimi.'],
  ['kërcënime', 'Kërcënimet duhet të merren seriozisht dhe mund të dënohen. Ruani provat dhe kërkoni ndihmë ligjore.'],
  ['varësi', 'Varësia është një sëmundje që mund të trajtohet. Ka qendra këshillimi për varësinë që ofrojnë mbështetje anonime.'],
  ['shëndet', 'Shëndeti juaj është i rëndësishëm. Mbani mend të bëni kontrolle të rregullta dhe të praktikoni marrëdhënie seksuale të sigurta.'],
  ['sëmundje', 'Nëse ndiheni e sëmurë, ju lutemi konsultohuni me një mjek. Ka shërbime speciale për punëtorët e seksit.'],
  ['infeksion seksualisht i transmetueshëm', 'Mbrojtja nga IST-të është thelbësore. Bëni teste rregullisht dhe përdorni gjithmonë prezervativë.'],
  ['sëmundje seksualisht e transmetueshme', 'Mbrojtja nga sëmundjet seksualisht të transmetueshme është thelbësore. Bëni teste rregullisht dhe përdorni gjithmonë prezervativë.'],
  ['prezervativë', 'Prezervativët janë mbrojtja juaj më e rëndësishme. Këmbëngulni gjithmonë në përdorimin e tyre dhe mbani tuajin.'],
  ['probleme me paratë', 'Shqetësimet financiare janë stresuese, por ka ndihmë. Kontaktoni një shërbim këshillimi për borxhet ose shërbimet sociale.'],
  ['strehim', 'Një strehim i sigurt është thelbësor. Nëse keni vështirësi, ka programe ndihme për personat e pastrehë ose në nevojë.'],
  ['dalje', 'Nëse dëshironi të dilni nga puna e seksit, ka qendra këshillimi të specializuara që mund t\'ju shoqërojnë në këtë rrugë.'],
  ['këshillim', 'Një këshillim i mirë mund të bëjë një ndryshim të madh. Ne mund t\'ju japim adresa të qendrave të specializuara të këshillimit.'],
  ['të drejta', 'Edhe si punonjëse seksi, ju keni të drejta. Informohuni për Ligjin për Mbrojtjen e Prostitucionit dhe situatën tuaj ligjore.'],
  ['regjistrim', 'Regjistrimi sipas Ligjit për Mbrojtjen e Prostitucionit mund t\'ju japë të drejta dhe garanci të caktuara. Kërkoni këshilla për këtë.'],
  ['polici', 'Në urgjenca ose në rast krimesh, mos hezitoni të telefononi policinë në 112.'],
  ['kontratë', 'Kontratat formale janë të rralla në punën e seksit, por marrëveshjet duhet të jenë të qarta. Në rast dyshimi, kërkoni këshilla ligjore.'],
  ['diskriminim', 'Diskriminimi është i papranueshëm. Nëse ndiheni të diskriminuar, mund të kontaktoni agjencitë kundër diskriminimit.'],
  ['ndihmë', 'Jemi këtu për t\'ju ndihmuar. Ju lutemi, përshkruani më hollësisht shqetësimin tuaj, në mënyrë që të gjej mbështetjen e duhur.'],
  ['emergjencë', 'Në rast urgjence akute, ju lutemi telefononi menjëherë 112 (policia/shërbimet e urgjencës).'],
  ['izolim', 'Ndjenjat e izolimit janë të vështira. Kërkoni kontakt me punonjës të tjerë seksi ose grupe mbështetëse.'],
  ['siguria online', 'Siguria juaj online është e rëndësishme. Mos ndani të dhëna personale të panevojshme dhe përdorni fjalëkalime të forta.'],
  ['kujdesi për veten', 'Shëndeti juaj mendor dhe fizik është thelbësor. Merrni kohë për veten dhe kërkoni ndihmë psikologjike nëse është e nevojshme.'],

  // --- Chinese (zh - Simplified Chinese) ---
  ['强奸', '这是一起严重的袭击。请立即寻求专业帮助，例如危机服务或报警。'],
  ['敲诈', '敲诈勒索是非法的，您并不孤单。请记录所有证据并向咨询中心寻求法律建议。'],
  ['暴力', '暴力是不可接受的。您的安全至关重要；请考虑是否应该拨打紧急电话110。'],
  ['强迫', '没有人可以强迫您做任何事情。有些组织可以帮助您摆脱强迫情况。'],
  ['殴打', '身体暴力是犯罪。请寻求医疗帮助并考虑报案。'],
  ['威胁', '威胁应认真对待，并可能受到惩罚。请保留证据并寻求法律援助。'],
  ['上瘾', '上瘾是一种可以治疗的疾病。有一些戒毒咨询中心提供匿名支持。'],
  ['健康', '您的健康很重要。请记住定期检查并进行安全性行为。'],
  ['疾病', '如果您感到不适，请去看医生。有专门为性工作者提供的服务。'],
  ['性传播感染', '预防性传播感染至关重要。请定期接受检测并始终使用避孕套。'],
  ['性病', '预防性病的传播至关重要。请定期接受检测并始终使用避孕套。'],
  ['避孕套', '避孕套是您最重要的保护。请务必坚持使用它们并随身携带。'],
  ['金钱问题', '财务问题令人感到压力，但可以获得帮助。请联系债务咨询服务或社会服务。'],
  ['住房', '安全的住房是基础。如果您遇到困难，有针对无家可归者或需要帮助的人的援助计划。'],
  ['退出', '如果您希望退出性工作，有专门的咨询中心可以陪伴您走这条路。'],
  ['咨询', '良好的咨询可以带来很大的改变。我们可以为您提供专业咨询中心的地址。'],
  ['权利', '即使作为性工作者，您也有权利。请了解《性工作者保护法》和您的法律状况。'],
  ['登记', '根据《性工作者保护法》进行登记可以为您提供某些权利和保障。请就此寻求建议。'],
  ['警察', '在紧急情况或犯罪情况下，请毫不犹豫地拨打110（或112）。'],
  ['合同', '在性工作中，正式合同很少见，但协议应明确。如有疑问，请寻求法律建议。'],
  ['歧视', '歧视是不可接受的。如果您感到受到歧视，可以联系反歧视机构。'],
  ['帮助', '我们在这里帮助您。请更详细地描述您的担忧，以便我找到适当的支持。'],
  ['紧急情况', '在紧急情况下，请立即拨打110（警察）或112（急救服务）。'],
  ['隔离', '孤独感很难受。请寻求与其他性工作者或支持团体的联系。'],
  ['网络安全', '您的网络安全很重要。请勿分享不必要的个人数据并使用强密码。'],
  ['自我关怀', '您的身心健康至关重要。请花时间照顾自己，并在需要时寻求心理帮助。'],

  // --- Thai (th) ---
  ['ข่มขืน', 'นี่คือการทำร้ายร่างกายอย่างร้ายแรง โปรดขอความช่วยเหลือจากผู้เชี่ยวชาญทันที เช่น บริการให้คำปรึกษาภาวะวิกฤตหรือตำรวจ'],
  ['แบล็กเมล์', 'การแบล็กเมล์เป็นสิ่งผิดกฎหมาย และคุณไม่ได้อยู่คนเดียว โปรดบันทึกทุกสิ่งและขอคำแนะนำทางกฎหมายจากศูนย์ให้คำปรึกษา'],
  ['ความรุนแรง', 'ความรุนแรงเป็นสิ่งที่ไม่ยอมรับได้ ความปลอดภัยของคุณสำคัญที่สุด; พิจารณาว่าคุณควรโทรสายด่วน 191 หรือไม่'],
  ['การบังคับ', 'ไม่มีใครสามารถบังคับคุณให้ทำอะไรได้ มีองค์กรที่สามารถช่วยให้คุณหลุดพ้นจากสถานการณ์การบังคับได้'],
  ['การทำร้ายร่างกาย', 'การใช้ความรุนแรงทางร่างกายเป็นอาชญากรรม โปรดขอความช่วยเหลือทางการแพทย์และพิจารณาการแจ้งความ'],
  ['การข่มขู่', 'การข่มขู่ควรได้รับการพิจารณาอย่างจริงจังและอาจเป็นอาชญากรรม โปรดเก็บหลักฐานและขอความช่วยเหลือทางกฎหมาย'],
  ['การติดยา', 'การติดยาเป็นโรคที่สามารถรักษาได้ มีศูนย์ให้คำปรึกษาด้านการติดยาที่ให้การสนับสนุนโดยไม่ระบุชื่อ'],
  ['สุขภาพ', 'สุขภาพของคุณเป็นสิ่งสำคัญ โปรดจำไว้ว่าต้องตรวจสุขภาพเป็นประจำและมีเพศสัมพันธ์ที่ปลอดภัย'],
  ['อาการป่วย', 'หากคุณรู้สึกไม่สบาย โปรดไปพบแพทย์ มีบริการพิเศษสำหรับผู้ให้บริการทางเพศ'],
  ['โรคติดต่อทางเพศสัมพันธ์', 'การป้องกันโรคติดต่อทางเพศสัมพันธ์เป็นสิ่งสำคัญ เข้ารับการตรวจเป็นประจำและใช้ถุงยางอนามัยเสมอ'],
  ['โรคทางเพศ', 'การป้องกันโรคทางเพศเป็นสิ่งสำคัญ เข้ารับการตรวจเป็นประจำและใช้ถุงยางอนามัยเสมอ'],
  ['ถุงยางอนามัย', 'ถุงยางอนามัยคือการป้องกันที่สำคัญที่สุดของคุณ โปรดยืนยันการใช้เสมอและพกพาไปด้วย'],
  ['ปัญหาทางการเงิน', 'ความกังวลทางการเงินเป็นเรื่องที่ตึงเครียด แต่ความช่วยเหลือมีอยู่จริง โปรดติดต่อบริการให้คำปรึกษาด้านหนี้สินหรือบริการสังคม'],
  ['ที่พักอาศัย', 'ที่พักที่ปลอดภัยเป็นสิ่งจำเป็น หากคุณกำลังประสบปัญหา มีโครงการช่วยเหลือสำหรับคนไร้บ้านหรือผู้ที่ต้องการความช่วยเหลือ'],
  ['การเลิกอาชีพ', 'หากคุณต้องการเลิกอาชีพบริการทางเพศ มีศูนย์ให้คำปรึกษาเฉพาะทางที่สามารถแนะนำคุณได้'],
  ['การให้คำปรึกษา', 'การให้คำปรึกษาที่ดีสามารถสร้างความแตกต่างอย่างมาก เราสามารถให้ที่อยู่ของศูนย์ให้คำปรึกษาเฉพาะทางแก่คุณได้'],
  ['สิทธิ', 'แม้จะเป็นผู้ให้บริการทางเพศ คุณก็มีสิทธิ โปรดศึกษาเกี่ยวกับกฎหมายคุ้มครองผู้ให้บริการทางเพศและสถานการณ์ทางกฎหมายของคุณ'],
  ['การลงทะเบียน', 'การลงทะเบียนภายใต้กฎหมายคุ้มครองผู้ให้บริการทางเพศสามารถให้สิทธิและหลักประกันบางอย่างแก่คุณได้ โปรดขอคำแนะนำเกี่ยวกับเรื่องนี้'],
  ['ตำรวจ', 'ในกรณีฉุกเฉินหรือกรณีอาชญากรรม อย่าลังเลที่จะโทรหาตำรวจที่ 191 (หรือ 112)'],
  ['สัญญา', 'สัญญาที่เป็นทางการหายากในงานบริการทางเพศ แต่ข้อตกลงควรชัดเจน หากมีข้อสงสัย โปรดขอคำแนะนำทางกฎหมาย'],
  ['การเลือกปฏิบัติ', 'การเลือกปฏิบัติเป็นสิ่งที่ยอมรับไม่ได้ หากคุณรู้สึกว่าถูกเลือกปฏิบัติ คุณสามารถติดต่อหน่วยงานต่อต้านการเลือกปฏิบัติได้'],
  ['ช่วยเหลือ', 'เราพร้อมให้ความช่วยเหลือคุณ โปรดอธิบายความกังวลของคุณให้ละเอียดขึ้นเพื่อให้ฉันสามารถหาการสนับสนุนที่เหมาะสมได้'],
  ['กรณีฉุกเฉิน', 'ในกรณีฉุกเฉินเฉียบพลัน โปรดโทร 191 (ตำรวจ) หรือ 1669 (รถพยาบาล) ทันที'],
  ['ความโดดเดี่ยว', 'ความรู้สึกโดดเดี่ยวเป็นเรื่องยาก โปรดติดต่อกับผู้ให้บริการทางเพศคนอื่นๆ หรือกลุ่มสนับสนุน'],
  ['ความปลอดภัยออนไลน์', 'ความปลอดภัยออนไลน์ของคุณเป็นสิ่งสำคัญ อย่าแชร์ข้อมูลส่วนบุคคลที่ไม่จำเป็นและใช้รหัสผ่านที่แข็งแกร่ง'],
  ['การดูแลตนเอง', 'สุขภาพกายและใจของคุณสำคัญมาก โปรดให้เวลาตัวเองและขอความช่วยเหลือทางจิตวิทยาหากจำเป็น'],

  // --- Vietnamese (vi) ---
  ['cưỡng hiếp', 'Đây là một vụ tấn công nghiêm trọng. Vui lòng tìm kiếm sự giúp đỡ chuyên nghiệp ngay lập tức, chẳng hạn như từ dịch vụ khủng hoảng hoặc cảnh sát.'],
  ['tống tiền', 'Tống tiền là bất hợp pháp và bạn không đơn độc. Hãy ghi lại mọi thứ và tìm kiếm lời khuyên pháp lý từ trung tâm tư vấn.'],
  ['bạo lực', 'Bạo lực là không thể chấp nhận được. An toàn của bạn là tối quan trọng; hãy xem xét liệu bạn có nên gọi số khẩn cấp 113 hay không.'],
  ['cưỡng bức', 'Không ai có thể ép buộc bạn làm bất cứ điều gì. Có những tổ chức có thể giúp bạn thoát khỏi các tình huống bị ép buộc.'],
  ['đánh đập', 'Bạo lực thể chất là một tội ác. Vui lòng tìm kiếm sự giúp đỡ y tế và cân nhắc việc trình báo.'],
  ['đe dọa', 'Các mối đe dọa phải được xem xét nghiêm túc và có thể bị trừng phạt. Hãy bảo quản bằng chứng và tìm kiếm sự hỗ trợ pháp lý.'],
  ['nghiện', 'Nghiện là một căn bệnh có thể điều trị được. Có các trung tâm tư vấn về nghiện cung cấp hỗ trợ ẩn danh.'],
  ['sức khỏe', 'Sức khỏe của bạn là quan trọng. Hãy nhớ kiểm tra sức khỏe định kỳ và thực hành tình dục an toàn.'],
  ['bệnh tật', 'Nếu bạn cảm thấy không khỏe, vui lòng đến gặp bác sĩ. Có các dịch vụ đặc biệt dành cho người hành nghề mại dâm.'],
  ['sti', 'Bảo vệ chống lại STIs là điều cần thiết. Hãy kiểm tra sức khỏe định kỳ và luôn sử dụng bao cao su.'],
  ['bệnh lây truyền qua đường tình dục', 'Bảo vệ chống lại bệnh lây truyền qua đường tình dục là điều cần thiết. Hãy kiểm tra sức khỏe định kỳ và luôn sử dụng bao cao su.'],
  ['bao cao su', 'Bao cao su là biện pháp bảo vệ quan trọng nhất của bạn. Luôn luôn yêu cầu sử dụng chúng và mang theo của riêng bạn.'],
  ['vấn đề tiền bạc', 'Những lo lắng về tài chính rất căng thẳng, nhưng có sự giúp đỡ. Liên hệ với dịch vụ tư vấn nợ hoặc các dịch vụ xã hội.'],
  ['nhà ở', 'Chỗ ở an toàn là điều cơ bản. Nếu bạn đang gặp khó khăn, có các chương trình hỗ trợ cho người vô gia cư hoặc những người cần giúp đỡ.'],
  ['thoát khỏi', 'Nếu bạn muốn thoát khỏi công việc mại dâm, có những trung tâm tư vấn chuyên biệt có thể đồng hành cùng bạn trên con đường này.'],
  ['tư vấn', 'Một cuộc tư vấn tốt có thể tạo ra sự khác biệt lớn. Chúng tôi có thể cung cấp cho bạn địa chỉ của các trung tâm tư vấn chuyên biệt.'],
  ['quyền lợi', 'Ngay cả khi là người hành nghề mại dâm, bạn cũng có quyền. Hãy tìm hiểu về Luật Bảo vệ Người hành nghề Mại dâm và tình trạng pháp lý của bạn.'],
  ['đăng ký', 'Đăng ký theo Luật Bảo vệ Người hành nghề Mại dâm có thể cung cấp cho bạn một số quyền và biện pháp bảo vệ nhất định. Hãy tìm lời khuyên về vấn đề này.'],
  ['cảnh sát', 'Trong trường hợp khẩn cấp hoặc phạm tội, đừng ngần ngại gọi cảnh sát theo số 113 (hoặc 112).'],
  ['hợp đồng', 'Hợp đồng chính thức hiếm khi có trong công việc mại dâm, nhưng các thỏa thuận phải rõ ràng. Nếu có nghi ngờ, hãy tìm kiếm lời khuyên pháp lý.'],
  ['phân biệt đối xử', 'Phân biệt đối xử là không thể chấp nhận được. Nếu bạn cảm thấy bị phân biệt đối xử, bạn có thể liên hệ với các cơ quan chống phân biệt đối xử.'],
  ['giúp đỡ', 'Chúng tôi ở đây để giúp bạn. Vui lòng mô tả chi tiết hơn mối quan tâm của bạn để tôi có thể tìm sự hỗ trợ phù hợp.'],
  ['khẩn cấp', 'Trong trường hợp khẩn cấp cấp tính, vui lòng gọi ngay 113 (cảnh sát) hoặc 115 (dịch vụ cấp cứu).'],
  ['cô lập', 'Cảm giác bị cô lập rất khó khăn. Hãy tìm cách liên hệ với những người hành nghề mại dâm khác hoặc các nhóm hỗ trợ.'],
  ['an toàn trực tuyến', 'An toàn trực tuyến của bạn là quan trọng. Đừng chia sẻ dữ liệu cá nhân không cần thiết và sử dụng mật khẩu mạnh.'],
  ['tự chăm sóc', 'Sức khỏe tinh thần và thể chất của bạn là rất quan trọng. Hãy dành thời gian cho bản thân và tìm kiếm sự giúp đỡ tâm lý nếu cần.'],

  // --- Kurdish (ku - Sorani) ---
  ['دەستدرێژی', 'ئەمە دەستدرێژییەکی جددییە. تکایە دەستبەجێ داوای یارمەتیی پیشەیی بکە، وەک خزمەتگوزاری قەیران یان پۆلیس.'],
  ['هەراسانکردن', 'هەراسانکردن نایاساییە و تۆ بەتەنیا نیت. هەموو شتێک تۆمار بکە و لە سەنتەرێکی ڕاوێژکاری داوای ئامۆژگاری یاسایی بکە.'],
  ['توندوتیژی', 'توندوتیژی قبووڵکراو نییە. سەلامەتیی تۆ لە پێشینەیە؛ بیر لەوە بکەرەوە ئایا پێویستە پەیوەندی بە ژمارەی فریاکەوتنی 112 بکەیت یان نا.'],
  ['زۆرکردن', 'کەس ناتوانێت تۆ ناچار بکات هیچ شتێک بکەیت. ڕێکخراو هەن کە دەتوانن یارمەتیت بدەن لە دۆخە زۆرلێکراوەکان ڕزگارت بێت.'],
  ['لێدان', 'توندوتیژی جەستەیی تاوانە. تکایە داوای یارمەتی پزیشکی بکە و بیر لە تۆمارکردنی سکاڵا بکەرەوە.'],
  ['هەڕەشە', 'هەڕەشەکان دەبێت بە جددی وەربگیرێن و دەتوانن سزابدرێن. بەڵگەکان بپارێزە و داوای یارمەتی یاسایی بکە.'],
  ['ئالوودەبوون', 'ئالوودەبوون نەخۆشییەکە کە دەتوانرێت چارەسەر بکرێت. سەنتەرەکانی ڕاوێژکاریی ئالوودەبوون هەن کە پاڵپشتیی بێناو پێشکەش دەکەن.'],
  ['تەندروستی', 'تەندروستیی تۆ گرنگە. بیرت بێت پشکنینی پەرودەمیی بکەیت و سێکسی سەلامەت بکەیت.'],
  ['نەخۆشی', 'ئەگەر هەستت بە نەخۆشی کرد، تکایە سەردانی پزیشک بکە. خزمەتگوزاریی تایبەت بە کرێکارانی سێکسی هەن.'],
  ['نەخۆشی سێکسی', 'پاراستن لە نەخۆشییە سێکسییەکان زۆر گرنگە. بە بەردەوامی پشکنین بکە و هەمیشە کۆندۆم بەکاربهێنە.'],
  ['کۆندۆم', 'کۆندۆم گرنگترین پارێزەری تۆیە. هەمیشە سووربە لەسەر بەکارهێنانیان و هی خۆت پێت بێت.'],
  ['کێشەی پارە', 'نیگەرانییە داراییەکان فشار دەخەنە سەر، بەڵام یارمەتی بەردەستە. پەیوەندی بە خزمەتگوزاریی ڕاوێژکاری قەرز یان خزمەتگوزارییە کۆمەڵایەتییەکانەوە بکە.'],
  ['نیشتەجێبوون', 'نیشتەجێبوونی سەلامەت بنەمایە. ئەگەر کێشەت هەیە، پرۆگرامەکانی یارمەتی هەن بۆ بێ ماڵەکان یان ئەوانەی پێویستیان بە یارمەتییە.'],
  ['وازهێنان', 'ئەگەر دەتەوێت واز لە کاری سێکسی بهێنیت، سەنتەرەکانی ڕاوێژکاریی تایبەتمەند هەن کە دەتوانن لەم ڕێگایەدا هاوڕێیەتیت بکەن.'],
  ['ڕاوێژکاری', 'ڕاوێژکارییەکی باش دەتوانێت جیاوازییەکی گەورە دروست بکات. دەتوانین ناونیشانی سەنتەرەکانی ڕاوێژکاریی تایبەتمەندت پێ بدەین.'],
  ['مافەکان', 'تۆش وەک کرێکارێکی سێکسی مافت هەیە. خۆت ئاگادار بکەرەوە لە یاسای پاراستنی لەشفرۆشی و دۆخی یاسایی خۆت.'],
  ['تۆمارکردن', 'تۆمارکردن بەپێی یاسای پاراستنی لەشفرۆشی دەتوانێت ماف و پارێزگاریی دیاریکراوت پێ ببەخشێت. لەم بارەیەوە ئامۆژگاری وەربگرە.'],
  ['پۆلیس', 'لە حاڵەتە کتوپڕەکان یان لە کاتی تاوانەکاندا، دوودڵ مەبە لە پەیوەندیکردن بە پۆلیسەوە لە 112.'],
  ['گرێبەست', 'گرێبەستە فەرمییەکان لە کاری سێکسیدا دەگمەنن، بەڵام ڕێککەوتنەکان دەبێت ڕوون بن. لە حاڵەتی گوماندا، داوای ئامۆژگاریی یاسایی بکە.'],
  ['جیاکاری', 'جیاکاری قبووڵکراو نییە. ئەگەر هەستت بە جیاکاری کرد، دەتوانیت پەیوەندی بە دەزگاکانی دژە-جیاکارییەوە بکەیت.'],
  ['یارمەتی', 'ئێمە لێرەین بۆ یارمەتیدانی تۆ. تکایە نیگەرانییەکەت بە وردی زیاتر باس بکە بۆ ئەوەی بتوانم پاڵپشتیی گونجاو بدۆزمەوە.'],
  ['فریاکەوتن', 'لە حاڵەتێکی کتوپڕی تونددا، تکایە دەستبەجێ پەیوەندی بە 112 (پۆلیس/خزمەتگوزاریی فریاکەوتن) بکە.'],
  ['دابڕان', 'هەستەکانی دابڕان قورسە. پەیوەندی بە کرێکارانی سێکسی تر یان گرووپەکانی پاڵپشتییەوە بکە.'],
  ['ئاسایشی ئۆنلاین', 'ئاسایشی تۆ لە ئۆنلاین گرنگە. زانیاریی کەسیی زیادە بڵاو مەکەرەوە و وشەی نهێنیی بەهێز بەکاربهێنە.'],
  ['خۆدروستکردن', 'تەندروستیی دەروونی و جەستەیی تۆ زۆر گرنگە. کاتێک بۆ خۆت تەرخان بکە و ئەگەر پێویست بوو، داوای یارمەتیی دەروونی بکە.'],

  // --- Arabic (ar) ---
  ['اغتصاب', 'هذا اعتداء خطير. يرجى طلب المساعدة المهنية فورًا، مثل خدمة الأزمات أو الشرطة.'],
  ['ابتزاز', 'الابتزاز غير قانوني ولست وحدك. وثّق كل شيء واطلب المشورة القانونية من مركز استشاري.'],
  ['عنف', 'العنف غير مقبول. سلامتك هي الأولوية القصوى؛ فكر فيما إذا كان يجب عليك الاتصال برقم الطوارئ 112.'],
  ['إكراه', 'لا أحد يستطيع إجبارك على فعل أي شيء. توجد منظمات يمكن أن تساعدك على التحرر من مواقف الإكراه.'],
  ['ضرب', 'العنف الجسدي جريمة. يرجى طلب المساعدة الطبية والنظر في تقديم بلاغ.'],
  ['تهديدات', 'يجب أخذ التهديدات على محمل الجد وقد تكون معاقبة. احتفظ بالأدلة واطلب المساعدة القانونية.'],
  ['إدمان', 'الإدمان مرض يمكن علاجه. توجد مراكز استشارية للإدمان تقدم دعمًا مجهول الهوية.'],
  ['صحة', 'صحتك مهمة. تذكر أن تجري فحوصات منتظمة وتمارس الجنس الآمن.'],
  ['مرض', 'إذا شعرت بالمرض، يرجى زيارة الطبيب. توجد خدمات خاصة للعاملين في مجال الجنس.'],
  ['عدوى منقولة جنسيا', 'الحماية من العدوى المنقولة جنسيًا ضرورية. احصل على اختبارات منتظمة واستخدم الواقي الذكري دائمًا.'],
  ['مرض جنسي', 'الحماية من الأمراض المنقولة جنسياً ضرورية. احصل على اختبارات منتظمة واستخدم الواقي الذكري دائمًا.'],
  ['واقي ذكري', 'الواقي الذكري هو أهم وسيلة حماية لك. اصر دائمًا على استخدامه واحتفظ بواقي خاص بك.'],
  ['مشاكل مالية', 'المخاوف المالية مرهقة، ولكن المساعدة متاحة. اتصل بخدمة استشارات الديون أو الخدمات الاجتماعية.'],
  ['سكن', 'السكن الآمن أساسي. إذا كنت تواجه صعوبات، توجد برامج مساعدة للمشردين أو المحتاجين.'],
  ['خروج', 'إذا كنت ترغب في الخروج من العمل الجنسي، توجد مراكز استشارية متخصصة يمكنها مرافقتك في هذا المسار.'],
  ['استشارة', 'الاستشارة الجيدة يمكن أن تحدث فرقًا كبيرًا. يمكننا تزويدك بعناوين مراكز الاستشارة المتخصصة.'],
  ['حقوق', 'حتى بصفتك عاملة في مجال الجنس، لديك حقوق. تعرف على قانون حماية البغايا ووضعك القانوني.'],
  ['تسجيل', 'يمكن أن يمنحك التسجيل بموجب قانون حماية البغايا حقوقًا وضمانات معينة. اطلب المشورة بشأن هذا الأمر.'],
  ['شرطة', 'في حالات الطوارئ أو في حالة الجرائم، لا تتردد في الاتصال بالشرطة على 112 (أو 999 في بعض البلدان).'],
  ['عقد', 'العقود الرسمية نادرة في العمل الجنسي، ولكن يجب أن تكون الاتفاقيات واضحة. في حالة الشك، اطلب المشورة القانونية.'],
  ['تمييز', 'التمييز غير مقبول. إذا شعرت بالتمييز، يمكنك الاتصال بوكالات مكافحة التمييز.'],
  ['مساعدة', 'نحن هنا لمساعدتك. يرجى وصف مخاوفك بمزيد من التفصيل حتى أتمكن من العثور على الدعم المناسب.'],
  ['طوارئ', 'في حالة الطوارئ الحادة، يرجى الاتصال فورًا بالرقم 112 (الشرطة / خدمات الطوارئ).'],
  ['عزلة', 'مشاعر العزلة صعبة. ابحث عن التواصل مع عاملين آخرين في مجال الجنس أو مجموعات دعم.'],
  ['الأمان عبر الإنترنت', 'سلامتك عبر الإنترنت مهمة. لا تشارك بيانات شخصية غير ضرورية واستخدم كلمات مرور قوية.'],
  ['رعاية ذاتية', 'صحتك العقلية والجسدية أمر بالغ الأهمية. خصص وقتًا لنفسك واطلب المساعدة النفسية إذا لزم الأمر.'],

  // --- Persian (fa) ---
  ['تجاوز', 'این یک حمله جدی است. لطفاً فوراً کمک حرفه‌ای، مانند خدمات بحران یا پلیس، را درخواست کنید.'],
  ['باج‌خواهی', 'باج‌خواهی غیرقانونی است و شما تنها نیستید. همه چیز را مستند کنید و از یک مرکز مشاوره حقوقی راهنمایی بخواهید.'],
  ['خشونت', 'خشونت غیرقابل قبول است. امنیت شما از اهمیت بالایی برخوردار است؛ در نظر بگیرید که آیا باید با شماره اضطراری 110 تماس بگیرید.'],
  ['اجبار', 'هیچ‌کس نمی‌تواند شما را به انجام کاری مجبور کند. سازمان‌هایی وجود دارند که می‌توانند به شما کمک کنند تا از موقعیت‌های اجباری رها شوید.'],
  ['ضرب و شتم', 'خشونت فیزیکی یک جرم است. لطفاً کمک پزشکی دریافت کنید و شکایت را در نظر بگیرید.'],
  ['تهدید', 'تهدیدات باید جدی گرفته شوند و می‌توانند مجازات داشته باشند. شواهد را حفظ کنید و از کمک حقوقی بهره‌مند شوید.'],
  ['اعتیاد', 'اعتیاد یک بیماری است که قابل درمان است. مراکز مشاوره اعتیاد وجود دارند که حمایت بی‌نام ارائه می‌دهند.'],
  ['سلامتی', 'سلامت شما مهم است. به یاد داشته باشید که معاینات منظم داشته باشید و روابط جنسی ایمن را تمرین کنید.'],
  ['بیماری', 'اگر احساس بیماری می‌کنید، لطفاً به پزشک مراجعه کنید. خدمات ویژه‌ای برای کارگران جنسی وجود دارد.'],
  ['عفونت مقاربتی', 'محافظت در برابر عفونت‌های مقاربتی ضروری است. به طور منظم آزمایش دهید و همیشه از کاندوم استفاده کنید.'],
  ['بیماری مقاربتی', 'محافظت در برابر بیماری‌های مقاربتی ضروری است. به طور منظم آزمایش دهید و همیشه از کاندوم استفاده کنید.'],
  ['کاندوم', 'کاندوم مهمترین محافظت شماست. همیشه بر استفاده از آن‌ها اصرار ورزید و کاندوم خود را همراه داشته باشید.'],
  ['مشکلات مالی', 'نگرانی‌های مالی استرس‌زا هستند، اما کمک در دسترس است. با خدمات مشاوره بدهی یا خدمات اجتماعی تماس بگیرید.'],
  ['مسکن', 'مسکن امن اساسی است. اگر مشکل دارید، برنامه‌های کمکی برای افراد بی‌خانمان یا نیازمند وجود دارد.'],
  ['خروج', 'اگر می‌خواهید از کار جنسی خارج شوید، مراکز مشاوره تخصصی وجود دارند که می‌توانند شما را در این مسیر همراهی کنند.'],
  ['مشاوره', 'مشاوره خوب می‌تواند تفاوت بزرگی ایجاد کند. ما می‌توانیم آدرس مراکز مشاوره تخصصی را به شما بدهیم.'],
  ['حقوق', 'حتی به عنوان یک کارگر جنسی، شما حقوقی دارید. خود را در مورد قانون حمایت از فاحشگی و وضعیت حقوقی خود آگاه کنید.'],
  ['ثبت نام', 'ثبت نام تحت قانون حمایت از فاحشگی می‌تواند حقوق و ضمانت‌های خاصی را به شما ارائه دهد. در این مورد مشاوره بگیرید.'],
  ['پلیس', 'در موارد اضطراری یا در صورت وقوع جرم، در تماس با پلیس درنگ نکنید. شماره اضطراری 110 یا 112 است.'],
  ['قرارداد', 'قراردادهای رسمی در کار جنسی نادر هستند، اما توافقات باید روشن باشند. در صورت تردید، از مشاوره حقوقی بهره‌مند شوید.'],
  ['تبعیض', 'تبعیض غیرقابل قبول است. اگر احساس تبعیض می‌کنید، می‌توانید با آژانس‌های ضد تبعیض تماس بگیرید.'],
  ['کمک', 'ما اینجا هستیم تا به شما کمک کنیم. لطفاً نگرانی خود را با جزئیات بیشتری توضیح دهید تا بتوانم پشتیبانی مناسب را پیدا کنم.'],
  ['فوری', 'در یک وضعیت اضطراری حاد، لطفاً فوراً با 110 (پلیس) یا 112 (خدمات اورژانس) تماس بگیرید.'],
  ['انزوا', 'احساس انزوا دشوار است. با سایر کارگران جنسی یا گروه‌های پشتیبانی ارتباط برقرار کنید.'],
  ['امنیت آنلاین', 'امنیت آنلاین شما مهم است. داده‌های شخصی غیرضروری را به اشتراک نگذارید و از رمزهای عبور قوی استفاده کنید.'],
  ['خودمراقبتی', 'سلامت روانی و جسمی شما بسیار مهم است. برای خود وقت بگذارید و در صورت نیاز کمک روان‌شناختی دریافت کنید.'],
  ]);


